name: flutter_chat_types
description: >
  Utility library for the flutter_chat_ui and flutter_firebase_chat_core libraries
  which contains shared type declarations.
version: 2.1.5
homepage: https://flyer.chat

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  equatable: ^2.0.2
  meta: ^1.3.0
